#!/bin/bash

# squash current diff, staged, or current commit into previous commit

git add -u
git commit -m tmp.$$

rev=$(git rev-parse HEAD^)

echo "Folding into:"
git log --format=%B HEAD^^..HEAD^

git reset --soft HEAD^^
git commit -C $rev
