#!/bin/bash

# squash staged changes into previous commit

if [[ "$(git diff --cached | wc -l)" = 0 ]]; then
    echo "nothing staged?"
    exit 1
fi

git commit -m tmp.$$

rev=$(git rev-parse HEAD^)

echo "Folding into:"
git log --format=%B HEAD^^..HEAD^

git reset --soft HEAD^^
git commit -C $rev
