#!/bin/bash

dir=$1

test -n $dir || dir=.

echo $(realpath $dir)
echo ------------------------------------------------

git -C $dir log --pretty=oneline --decorate
echo ------------------------------------------------
git -C $dir status
