#!/bin/bash

set -x
set -e

dest=~/src/master-headnode/cache/

function docopy() {
	file=$1
	link=$2

	rm -f $dest/$link
	cp $file $dest/
	(cd $dest && ln -s $file $link)

}

cd output/

docopy boot*.tgz file.platboot.tgz
docopy $(readlink platform-latest.tgz) file.platform.tgz
docopy images*.tgz file.platimages.tgz

echo export NO_DOWNLOAD=1
