#!/bin/bash

set -x

cd output/
cp boot*.tgz ~/src/sdc-headnode/cache/file.platboot.tgz
cp platform-latest.tgz ~/src/sdc-headnode/cache/file.platform.tgz
cp images*.tgz ~/src/sdc-headnode/cache/file.platimages.tgz

echo export NO_DOWNLOAD=1
