#!/bin/bash

# FIXME: won't work for aggregeations, see
# https://docs.joyent.com/private-cloud/troubleshooting/reset

uuid=$1

set -e
set -x

[ -n "$uuid" ] || exit 1

#macs=$(sdc-napi /nics | json -Ha belongs_to_uuid mac | awk "\"$uuid\" == \$1 { print \$2 }")

# json defeated me for pulling this out. It's better than the above as it won't
# leave lingering entries that screw everything up.
#
macs=$(sdc-cnapi --no-headers /servers/$uuid | json sysinfo."Network Interfaces" | grep "MAC Address" | sed 's+.*MAC Address": "++;s+".*$++')

echo "Yes" | sdc-server delete $uuid

for mac in $macs; do
	sdc-napi --no-headers /nics/$mac -X DELETE
done

echo "Now sdc-factoryreset on the CN"
