#!/bin/sh
# From Gerrit Code Review 3.0.3
#
# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# modified from gerrit upstream to work offline

src="$(mktemp)"
git log --format=%B -1 HEAD | git stripspace >$src

# $RANDOM will be undefined if not using bash, so don't use set -u
random=$( (whoami ; hostname ; date; cat $src ; echo $RANDOM) | git hash-object --stdin)
dest="$(mktemp)"

trap 'rm -f $src $dest' EXIT

# Avoid the --in-place option which only appeared in Git 2.8
# Avoid the --if-exists option which only appeared in Git 2.15
if ! git -c trailer.ifexists=doNothing interpret-trailers \
      --trailer "Change-Id: I${random}" < "$src" > "${dest}" ; then
  echo "cannot insert change-id line in $dest"
  exit 1
fi

cmp $src $dest || git commit --amend -F $dest
