#!/bin/bash

# squash current diff, staged, or current commit into previous commit

git add -u
git commit -m tmp.$$
git reset --soft HEAD~2

echo "Folding into:"
git log --format=%B HEAD@{2}^..HEAD@{2}
git commit -m "$(git log --format=%B HEAD@{2}^..HEAD@{2})"
