#!/usr/bin/env node

// send a command to the haproxy socket

var net = require('net');

var path = '/tmp/haproxy';

var client = net.connect(path, function (err) {
  if (err)
    process.exit(1);
  client.end(process.argv[1] + '\n');
});

client.on('data', function(data) {
  client.end();

  // the data comes as a buffer so make it a string
  console.log(data.toString());
});
