#!/bin/bash

set -e

me=$(basename $0)
mkdir -p /var/tmp/$me.$$
cd /var/tmp/$me.$$
curl -k -o image.manifest "https://updates.joyent.com/images/$1?channel=experimental"
curl -k -o image.img "https://updates.joyent.com/images/$1/file?channel=experimental"
imgadm install -m image.manifest -f image.img
#rm image.manifest image.img
echo $1
