#!/bin/bash

#set -x
set -e

echo 'making clean'
make clean >c.out 2>&1

echo 'making smatch'
SHADOW_CCS=smatch,$CODEMGR_WS/usr/src/tools/proto/root_$MACH-nd/opt/onbld/bin/$MACH/smatch,smatch make all install 2>&1 | tee m.out | grep smatch: || /bin/true

if !  grep smatch: m.out >/dev/null; then
	exit 0
fi

echo 'smatch failed !!!'
