#!/bin/bash

#set -x

echo 'making clean'
make clean >c.out 2>&1 || {
	echo "clean failed" >&2
	exit 1
}

echo 'making smatch'
export SHADOW_CCS=smatch,$CODEMGR_WS/usr/src/tools/proto/root_$MACH-nd/opt/onbld/bin/$MACH/smatch,smatch

ret=0

make all install >m.out 2>&1 || ret=1

if grep smatch: m.out; then
	ret=1
fi

if [[ "$ret" = 1 ]]; then
	echo 'make with smatch failed'
	tail m.out
fi

exit $ret
