#!/bin/bash

# given a platform TGZ, mount its /

set -e

tgz=$(realpath $1)

mkdir /tmp/tmp.$$
cd /tmp/tmp.$$
tar xzf $tgz
mkdir mnt
pfexec mount -F ufs platform*/i86pc/amd64/boot_archive mnt/
echo /tmp/tmp.$$/mnt/
