#!/bin/bash

#
# attempt to dump both userspace and kernel stacks for a process's  thread
#

set -f

IFS=/ read pid tids <<< $1

if [[ -z "$tids" ]]; then
	tids=$(ps -L -p $pid -o lwp | sed 1d)
fi

mdbin=""

if [[ "$tids" -eq 0 ]]; then
	echo "No userspace threads left for $pid"
	mdb -ke "0t$pid::pid2proc | ::walk thread | ::findstack -v"
	exit 0
fi

for tid in $tids; do
	mdbin+="::echo ========== $pid/$tid ============================ ;"
	mdbin+=$(pstack $pid/$tid | sed 's/\(.*\)/; ::echo "\1"/')
	mdbin+="; 0t$pid::pid2proc | ::walk thread thr | ::print -d kthread_t t_tid | ::grep '.==0t$tid' | ::eval <thr=K | ::findstack -v ;"
done

#echo $mdbin

echo "$mdbin" | mdb -k
