#!/bin/bash

while read ln; do
	line=$(echo $ln | sed 's+\(.*\)\([0-9]m[0-9]*\.[0-9]*s\)\(.*\)$+\1FOO\3+')
	i=$(echo $ln | sed 's+\(.*\)\([0-9]m[0-9]*\.[0-9]*s\)\(.*\)$+\2+')
	min=$(echo $i | sed 's/m.*//')
	sec=$(echo $i | sed 's/.*m\(.*\)s.*/\1/;s/\..*$//' )
	subsec=$(echo $i | sed 's/.*m[0-9]*\.\(.*\)s.*/\1/;')
	time=$(( 60 * $min + $sec )).$subsec
	echo $line | sed "s+FOO+$time+"
done
