#!/bin/bash

rev=$1
shift

#to=levon@movementarian.org
to=advocates@lists.illumos.org

bugid=$(git log --format=%B -1 $rev | head -1)
git format-patch --stdout -1 $rev >$rev.patch

echo $* | cat ~/src/grot/advocates-mail.txt - | mutt -s "[PATCH] $bugid" -a $rev.patch -- $to
