#!/bin/bash

speaker_out=alsa_output.pci-0000_00_1f.3.analog-stereo
headset_out=alsa_output.usb-0b0e_Jabra_Link_370_745C4BEB6B40-00.analog-stereo
headset_in=alsa_input.usb-0b0e_Jabra_Link_370_745C4BEB6B40-00.analog-mono

hdmi_out=alsa_output.pci-0000_00_1f.3.hdmi-stereo-extra1
default_out=alsa_output.pci-0000_00_1f.3.analog-stereo

if test $1 == "on"; then
	pactl set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
else
	pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi
