#!/bin/bash

speaker_out=alsa_output.pci-0000_00_1f.3.analog-stereo
headset_out=alsa_output.usb-0b0e_Jabra_Link_370_745C4BEB6B40-00.analog-stereo
headset_in=alsa_input.usb-0b0e_Jabra_Link_370_745C4BEB6B40-00.analog-mono
alesis_in=alsa_input.usb-Alesis_io_2-00.analog-stereo
# FIXME: usb card

if test $1 == "on"; then
	pactl set-default-source $headset_in
	pactl set-default-sink $headset_out
else
	pactl set-default-source $alesis_in
	pactl set-default-sink $speaker_out
fi
