#!/bin/bash

# Do some post-setup stuff

host=root@$1

shift

#set -e
set -x

keykill $host
ssh-copy-id $host
ssh $host sdc-usbkey mount
scp ~/.ssh/authorized_keys $host:/mnt/usbkey/config.inc/root.authorized_keys

ssh $host zfs create zones/jlevon
ssh $host /opt/smartdc/bin/sdc-usbkey mount

ssh $host /opt/smartdc/bin/sdcadm post-setup common-external-nics
ssh $host /opt/smartdc/bin/sdcadm post-setup cloudapi
ssh $host /opt/smartdc/bin/sdcadm post-setup dev-headnode-prov
ssh $host /opt/smartdc/bin/sdcadm post-setup dev-sample-data

ssh-add -L | head -1 >/tmp/pkey.$$.pub
scp /tmp/pkey.$$.pub $host:/tmp/pkey.$$.pub
ssh $host /opt/smartdc/bin/sdc-useradm add-key admin /tmp/pkey.$$.pub


if [[ "$1" != "manta" ]] ; then
	exit 0
fi

[[ -f ~/src/lab/emy-15.manta.json ]] || exit 1

ssh $host /usbkey/scripts/setup_manta_zone.sh

scp ~/src/lab/emy-15.manta.json $host:/zones/jlevon/
manta0=$(ssh $host vmadm lookup alias=manta0)
ssh $host ln -s /zones/$manta0/root/opt/smartdc/manta-deployment/networking /var/tmp/networking
ssh $host "(cd /var/tmp/networking && . /root/.profile && ./manta-net.sh /zones/jlevon/emy-15.manta.json)"
ssh $host zlogin $manta0 'bash -c ". /root/.profile ; manta-init -s lab -e root"'
sleep 60

ssh $host /opt/smartdc/bin/sdc-useradm add-key poseidon /tmp/pkey.$$.pub

echo "Now run:"

echo zlogin $manta0
echo manta-deploy-lab && manta-adm alarm config update -y

exit 0

