#!/bin/bash

# ctags misses all of the assembly entry points: add them manually

# cmt_ev_thread_swtch     common/disp/cmt.c       /^cmt_ev_thread_swtch(pg_t # *pg, cpu_t *cp, hrtime_t now, kthread_t *old,$/;"    f       file:

exctags -R
mv tags t.$$

egrep 'ALTENTRY\(.*\)|ENTRY\(.*\)|ENTRY_NP\(.*\)' intel/ia32/ml/*.s i86pc/ml/*.s | while read ln; do
	file=$(echo $ln | sed 's/^\([.0-9a-z_/]*\):.*/\1/')
	func=$(echo $ln | gsed 's/^.*:.*\(ENTRY\|ENTRY_NP\|ALTENTRY\)(\(.*\)).*/\2/')
	match="$(echo "$ln" | sed 's/^.*://')"
	echo "$func	$file	/^$match/;\"	f	file" >>t.$$
done

sort t.$$ >tags
rm t.$$
