#!/bin/bash

url="$1"

umask 0022

readonly LOG_FILE="/var/log/jlevon/download.log"
touch $LOG_FILE
exec 1>>$LOG_FILE
exec 2>&1

#set -x

if grep "$1" ~/shared/podcasts/downloaded >/dev/null; then
	echo "$(date): skipping $1"
	exit 0
fi

echo "$(date): downloading $1"

echo "$1" >>~/shared/podcasts/downloaded

cd /home/jlevon/shared/podcasts/incoming/

/home/jlevon/src/curl/src/curl --no-clobber -RksSLJO "$1"
