#!/bin/bash

set -x

umask 0022

cd /home/jlevon/shared/podcasts/incoming/

~/src/get_iplayer/get_iplayer --pid-recursive https://www.bbc.co.uk/sounds/brand/p0d6bs79
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Ravenscroft
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Agendum
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Eldon
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Riches
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Herring
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Poets
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get Grounded
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get "Jason Cook"
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get "Armando"
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get "So Wrong"
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get "Chain Reaction"
/home/jlevon/src/get_iplayer/get_iplayer --type=radio --get "Tim Key"

for i in *.m4a; do
	ffmpeg -i "$i" "$i".mp3
done

rm -f *.m4a
