#!/bin/sh

boxes=

for i in `ls -t $HOME/Mail/`;
do
	if test -d $HOME/Mail/$i -a "$i" != "outbox" -a "$i" != "junk" -a "$i" != "bounces" -a "$i" != "trash" -a "$i" != "html"; then
		boxes="$boxes +$i"
		#if test `ls -1 $HOME/Mail/$i/new/ 2>/dev/null | wc -l` -ne 0; then
		#	boxes="$boxes +$i"
		#elif test `ls -1 $HOME/Mail/$i/cur/ 2>/dev/null | wc -l` -ne 0; then
		#	boxes="$boxes +$i"
		#fi
	fi
done
echo $boxes
