#!/bin/sh

MAILDIR=$HOME/Mail/
FOLDERS=
for i in `ls $MAILDIR`; do
        if test "$i" = "trash"; then
                continue;
        fi
        if test "$i" = "linux"; then
                continue;
        fi
        if test -n "`ls $MAILDIR/$i/new/ 2>/dev/null`"; then
                FOLDERS="$FOLDERS$i "
        fi
done

if test -n "$FOLDERS"; then
        echo "New mail in $FOLDERS"
fi

exit 0
