#!/bin/bash

#
# Copy this file and jlevon.ml to /opt/custom/smf
# then svcadm restart manifest-import
#

set -e
set -x

mkdir -m 700 -p /root/.ssh/ || true

cat /zones/jlevon/authorized_keys >>~/.ssh/authorized_keys
