#!/bin/bash

JOB_NAME=$1
JOB_ID=$2
[[ -n $JOB_ID ]] || JOB_ID=lastBuild

token=$(cat ~/.jenkinstoken)

echo "Grabbing https://jenkins.joyent.us/job/${JOB_NAME}/${JOB_ID}/consoleText"
curl -u "john.levon:$token" -O "https://jenkins.joyent.us/job/${JOB_NAME}/${JOB_ID}/consoleText"

