#!/bin/bash

JOB_NAME=$1
JOB_ID=$2
[[ -n $JOB_ID ]] || JOB_ID=lastBuild

token=$(cat ~/.jenkinstoken)

url="https:///jenkins.joyent.us/job/joyent-org/job/${JOB_NAME}/job/master/${JOB_ID}/consoleText"
echo "Grabbing $url"
curl -u "john.levon:$token" -O "$url"

