#!/bin/bash

# Given a commit, build and upload a webrev based upon the commit's bug ID.

set -e
#set -x

rev=$1


bugid=$(git log --format=%B -1  $rev | head -1 | awk '{print $1}')

rm -rf $SRC/../../webrev

cwebrev -c $rev -t rsync://webrev@cr.illumos.org:$bugid -U

echo
echo "http://cr.illumos.org/~webrev/jlevon/$bugid"
