#!/bin/bash

by=$*
if [[ "$by" = "toomas" ]]; then
	by="Toomas Soome <tsoome@me.com>"
elif [[ "$by" = "rm" ]]; then
	by="Robert Mustacchi <rm@fingolfin.org>"
fi

git log -1 --format=format:%B >/tmp/tmp.$$
echo "Reviewed by: $by" >>/tmp/tmp.$$
git commit --amend -F /tmp/tmp.$$
rm /tmp/tmp.$$
