#!/bin/bash

# our sshd defaults to ChallengeResponseAuthentication yes,
# but doesn't even list it in the config!

echo "ChallengeResponseAuthentication no" >>/etc/ssh/sshd_config
svcadm restart ssh
