#!/bin/bash

#cat - >/tmp/pp.$$
cat - | perl -MMIME::QuotedPrint -0777 -nle 'print decode_qp($_)' | sed '/urldefense.proofpoint.com/{s+\&d=.*++;s+https://urldefense.proofpoint.com/v2/url?u=++;s+_+/+g;s+-3A+:+g;s+-2D+-+g;s+-23+#+;s+-5F+_+g;s+-3F+?+g;s+-3D+=+g;s+-26+\&+g;}'
