#!/bin/bash

topic=$1

remote=origin
if git remote get-url gerrit 2>/dev/null; then
	remote=gerrit
	parent=gerrit/master
	git fetch gerrit
else
	parent=${2:-$(git parent-branch $remote)}
fi

nr_commits=$(git log --oneline $parent..HEAD | wc -l)

if [[ $nr_commits != 1 ]]; then
	echo "WARNING: more than one commit since $parent found"
else
    gerrit-change-id
fi

args=""
if [[ -n "$topic" ]]; then
    args="-o topic=$topic"
fi

echo "Commits:"
echo "  --------------"
git log --oneline $parent..HEAD
echo "  --------------"

parentbranch=${parent#*/}
git push -n $args $remote HEAD:refs/for/$parentbranch

echo "  --------------"
echo "  git push $remote $args HEAD:refs/for/$parentbranch"
echo "  --------------"

