#!/bin/bash

topic=$1
parent=${2:-$(git parent-branch)}
nr_commits=$(git log --oneline $parent..HEAD | wc -l)

if [[ $nr_commits != 1 ]]; then
	echo "WARNING: more than one commit since $parent found"
else
    gerrit-change-id
fi

args=""
if [[ -n "$topic" ]]; then
    args="-o topic=$topic"
fi

echo "Commits:"
echo "  --------------"
git log --oneline $parent..HEAD
echo "  --------------"

parentbranch=${parent#*/}
git push -n $args origin HEAD:refs/for/$parentbranch

echo "  --------------"
echo "  git push origin $args HEAD:refs/for/$parentbranch"
echo "  --------------"

