#!/bin/bash

parent=$(git parent-branch)
nr_commits=$(git log --oneline $parent..HEAD | wc -l)

topic=$1

if [[ $nr_commits != 1 ]]; then
	echo "WARNING: more than one commit since $parent found"
else
    gerrit-change-id
fi

args=""
if [[ -n "$topic" ]]; then
    args="-o topic=$topic"
fi

echo "Commits:"
echo "  --------------"
git log --oneline $parent..HEAD
echo "  --------------"

parentbranch=${parent#*/}
git push -n $args origin HEAD:refs/drafts/$parentbranch

echo "  --------------"
echo "  git push origin $args HEAD:refs/drafts/$parentbranch"
echo "  --------------"

