#!/bin/bash

parent=$(git parent-branch)
nr_commits=$(git log --oneline $parent..HEAD | wc -l)

topic=$1

if [[ $nr_commits != 1 ]]; then
	echo "WARNING: $nr_commits commits since $parent found"
fi

gerrit-change-id

args=""
if [[ -n "$topic" ]]; then
    args="-o topic=$topic"
fi

parentbranch=${parent#*/}
git push -n $args origin HEAD:refs/drafts/$parentbranch

echo "  --------------"
echo "  git push origin $args HEAD:refs/drafts/$parentbranch"
echo "  --------------"

