#!/usr/bin/python3

import re
import sys
import fileinput

for line in fileinput.input():
    newline = re.sub(r'(\d+)m(\d+(\.\d+)?)s',
                     lambda m: f'{float(m.group(1)) * 60 + float(m.group(2))} s',
                     line)
    print(newline, end='')
