#!/bin/bash

# output to both a named file and stdout, but don't exit on hup.
# Is there a better way?

teefile=$(echo $* | sed 's+[. /-]+_+g').out

>$teefile
tail -f $teefile &
tpid=$!

trap "kill $tpid" EXIT
nohup "$@" >$teefile
