#!/usr/bin/env python3

import sys
import re

def usage():
        print("unit 200 ms")
        print("time units: ns,us,ms,s,m,h,d")
        print("byte units: bit,B,Bl,Kb,p,Kbit,Mb,Mbit,Gb,Gbit,Tb")
        print("Bl = 512 bytes")
        sys.exit(1)


if len(sys.argv) == 1:
	val = int(input(), 0)
	unit = "B"
elif len(sys.argv) == 2:
	val = int(input(), 0)
	unit = sys.argv[1]
elif len(sys.argv) == 3:
	val = int(sys.argv[1], 0)
	unit = sys.argv[2]
else:
        usage()


times = {
        "ns": ( 1000000000, "nanoseconds" ),
        "us": ( 1000000, "microseconds" ),
        "ms": ( 1000, "milliseconds" ),
        "s": ( 1, "seconds" ),
        "m": ( 0.0166666667, "minutes" ),
        "h": ( 0.000277777778, "hours" ),
        "d": ( 1.15740741e-5, "days" ),
}

bytes = {
    "bit": (8, "bits"),
    "B": (1, "bytes"),
    "KiB": (1/1024.0, "kibibytes"),
    "KB": (1/1000.0, "kilobytes"),
    "MiB": (1/(1024.0 * 1024.0), "mibibytes"),
    "MB": (1/(1000.0 * 1000.0), "megabytes"),
    "GiB": (1/(1024.0 * 1024.0 * 1024.0), "gibibytes"),
    "GB": (1/(1000.0 * 1000.0 * 1000.0), "gigabytes"),
    "Gbit": (8/(1000.0 * 1000.0 * 1000.0), "gigabits"),

    "Bl": (1/512.0, "512-bytes blocks"),
    "p": (1/4096.0, "(4Kb) pages"),
    "Lp": (1/2097152.0, "(2Mb) large pages"),
    "P": (1/8.0, "64-bit pointers"),
    "s1gblink": (8 / (1000.0 * 1000.0 * 1000.0), "seconds over 1Gbit link"),
    "s10gblink": (8 / (10 * 1000.0 * 1000.0 * 1000.0), "seconds over 10Gbit link"),
}

# bytes = {
#         "bit": ( 1024 * 8, "bits" ),
#         "B": ( 1024, "bytes" ),
#         "KB": ( 1, "kilobytes" ),
#         "Kb": ( 8192 / 1000.0, "kilobits" ),
#         "Mb": ( 8192 / (1000.0 * 1000.0), "megabits" ),
#         "Gb": ( 8192 / (1000.0 * 1000.0 * 1000.0), "gigabits" ),
#         "MB": ( 1/1024.0, "megabytes" ),
#         "GB": ( 1/(1000.0 * 1000.0), "gigabytes" ),
#         "GiB": ( 1/(1024.0 * 1024.0), "gibibytes" ),
#         "TB": ( 1/(1024.0 * 1024.0 * 1024.0), "terabytes" ),
# }

if unit in times.keys():
        table = times
elif unit in bytes.keys():
        table = bytes
else:
        print("unknown unit %s" % unit)
        sys.exit(1)

norm = float(val) / table[unit][0]

for key, val in sorted(table.items(), key=lambda x:x[1][0]):
        print("%f %s" % (norm * val[0], val[1]))

