#!/bin/bash

for pid in $(pgrep bhyve); do
	zone=$(ps -p $pid -o zone=)
	echo "============== zone pid $pid $(vmadm list -Ho alias uuid=$zone) ($zone) ==============="
	/zones/jlevon/lwpinfo $pid
done

declare -A cpus

for pid in $(pgrep bhyve); do
	zone=$(ps -p $pid -o zone=)
	alias=$(vmadm list -Ho alias uuid=$zone)
	for cpu in $(/zones/jlevon/lwpinfo $pid  | grep bind:[0-9] | cut -d: -f 4); do
		#echo $alias $cpu
		cpus+=(["$cpu"]+="$alias ")
	done
done

psrinfo -vp | while read line; do
	htcpus=$(echo $line | grep "2 virtual" | sed 's+.*(++;s+)++;')
	echo $line
	out=""
	for cpu in $htcpus; do
		if test "${cpus[$cpu]}"; then
			out="$out$cpu: ${cpus[$cpu]}"
		fi
	done
	if [ -n "$out" ]; then
		echo $out
	fi
done
